import "./globals.css";
import { Inter } from "next/font/google";
import "prism-themes/themes/prism-dracula.css";
import "../styles/code.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          src={"//at.alicdn.com/t/c/font_4132358_4i5a1eu91ni.js"}
        ></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
