export const fileIcon = [
  {
    name: "yarn",
    fileNames: [
      ".yarnrc",
      "yarn.lock",
      ".yarnclean",
      ".yarn-integrity",
      "yarn-error.log",
      ".yarnrc.yml",
      ".yarnrc.yaml",
    ],
  },
  {
    name: "vite",
    fileNames: [
      "vite.config.js",
      "vite.config.mjs",
      "vite.config.cjs",
      "vite.config.ts",
      "vite.config.cts",
      "vite.config.mts",
    ],
  },
  {
    name: "video",
    fileExtensions: [
      "webm",
      "mkv",
      "flv",
      "vob",
      "ogv",
      "ogg",
      "gifv",
      "avi",
      "mov",
      "qt",
      "wmv",
      "yuv",
      "rm",
      "rmvb",
      "mp4",
      "m4v",
      "mpg",
      "mp2",
      "mpeg",
      "mpe",
      "mpv",
      "m2v",
    ],
  },
  {
    name: "image",
    fileExtensions: [
      "png",
      "jpeg",
      "jpg",
      "gif",
      "ico",
      "tif",
      "tiff",
      "psd",
      "psb",
      "ami",
      "apx",
      "avif",
      "bmp",
      "bpg",
      "brk",
      "cur",
      "dds",
      "dng",
      "exr",
      "fpx",
      "gbr",
      "img",
      "jbig2",
      "jb2",
      "jng",
      "jxr",
      "pgf",
      "pic",
      "raw",
      "webp",
      "eps",
      "afphoto",
      "ase",
      "aseprite",
      "clip",
      "cpt",
      "heif",
      "heic",
      "kra",
      "mdp",
      "ora",
      "pdn",
      "reb",
      "sai",
      "tga",
      "xcf",
      "jfif",
      "ppm",
      "pbm",
      "pgm",
      "pnm",
      "icns",
    ],
  },
  {
    name: "babel",
    fileNames: [
      ".babelrc",
      ".babelrc.cjs",
      ".babelrc.js",
      ".babelrc.mjs",
      ".babelrc.json",
      "babel.config.cjs",
      "babel.config.js",
      "babel.config.mjs",
      "babel.config.json",
      "babel-transform.js",
      ".babel-plugin-macrosrc",
      ".babel-plugin-macrosrc.json",
      ".babel-plugin-macrosrc.yaml",
      ".babel-plugin-macrosrc.yml",
      ".babel-plugin-macrosrc.js",
      "babel-plugin-macros.config.js",
    ],
  },
  { name: "editorconfig", fileNames: [".editorconfig"] },
  {
    name: "audio",
    fileExtensions: ["mp3", "flac", "m4a", "wma", "aiff", "wav"],
  },
  {
    name: "font",
    fileExtensions: [
      "woff",
      "woff2",
      "ttf",
      "eot",
      "suit",
      "otf",
      "bmap",
      "fnt",
      "odttf",
      "ttc",
      "font",
      "fonts",
      "sui",
      "ntf",
      "mrf",
    ],
  },
  {
    name: "database",
    fileExtensions: [
      "pdb",
      "sql",
      "pks",
      "pkb",
      "accdb",
      "mdb",
      "sqlite",
      "sqlite3",
      "pgsql",
      "postgres",
      "psql",
      "db",
      "db3",
    ],
  },
  {
    name: "eslint",
    fileNames: [
      ".eslintrc.js",
      ".eslintrc.cjs",
      ".eslintrc.yaml",
      ".eslintrc.yml",
      ".eslintrc.json",
      ".eslintrc-md.js",
      ".eslintrc-jsdoc.js",
      ".eslintrc",
      ".eslintignore",
      ".eslintcache",
      "eslint.config.js",
      "eslint.config.mjs",
    ],
  },
  { name: "prisma", fileNames: ["prisma.yml"], fileExtensions: ["prisma"] },
  {
    name: "pnpm",
    light: true,
    fileNames: ["pnpm-lock.yaml", "pnpm-workspace.yaml", ".pnpmfile.cjs"],
  },
  { name: "react", fileExtensions: ["jsx"] },
  { name: "react_ts", fileExtensions: ["tsx"] },
  {
    name: "nginx",
    fileNames: ["nginx.conf"],
    fileExtensions: ["nginx", "nginxconf", "nginxconfig"],
  },
  {
    name: "license",
    fileExtensions: ["cer", "cert", "crt"],
    fileNames: [
      "copying",
      "copying.md",
      "copying.rst",
      "copying.txt",
      "copyright",
      "copyright.md",
      "copyright.rst",
      "copyright.txt",
      "license",
      "license-agpl",
      "license-apache",
      "license-bsd",
      "license-mit",
      "license-gpl",
      "license-lgpl",
      "license.md",
      "license.rst",
      "license.txt",
      "licence",
      "licence-agpl",
      "licence-apache",
      "licence-bsd",
      "licence-mit",
      "licence-gpl",
      "licence-lgpl",
      "licence.md",
      "licence.rst",
      "licence.txt",
    ],
  },
  { name: "python", fileExtensions: ["py"] },
  {
    name: "javascript-map",
    fileExtensions: ["js.map", "mjs.map", "cjs.map"],
  },
  { name: "javascript", fileExtensions: ["esx", "mjs", "js"] },
  { name: "css-map", fileExtensions: ["css.map"] },
  { name: "css", fileExtensions: ["css"] },
  { name: "sass", fileExtensions: ["scss", "sass"] },
  { name: "less", fileExtensions: ["less"] },
  {
    name: "yaml",
    fileExtensions: ["yml", "yaml", "yml.dist", "yaml.dist", "YAML-tmLanguage"],
  },
  {
    name: "json",
    fileExtensions: [
      "json",
      "jsonc",
      "tsbuildinfo",
      "json5",
      "jsonl",
      "ndjson",
    ],
    fileNames: [
      ".jscsrc",
      ".jshintrc",
      "composer.lock",
      ".jsbeautifyrc",
      ".esformatter",
      "cdp.pid",
      ".lintstagedrc",
    ],
  },
  {
    name: "nodejs",
    fileNames: [
      "package.json",
      "package-lock.json",
      ".nvmrc",
      ".esmrc",
      ".node-version",
    ],
  },
  { name: "vue", fileExtensions: ["vue"] },
  {
    name: "typescript-def",
    fileExtensions: ["d.ts", "d.cts", "d.mts"],
  },
  {
    name: "typescript",
    fileExtensions: ["ts"],
  },
  { name: "document", fileExtensions: ["txt"] },
  {
    name: "git",
    fileExtensions: ["patch"],
    fileNames: [
      ".git",
      ".gitignore",
      ".gitmessage",
      ".gitignore-global",
      ".gitignore_global",
      ".gitattributes",
      ".gitattributes-global",
      ".gitattributes_global",
      ".gitconfig",
      ".gitmodules",
      ".gitkeep",
      ".keep",
      ".gitpreserve",
      ".gitinclude",
      ".git-blame-ignore",
      ".git-blame-ignore-revs",
      ".git-for-windows-updater",
      "git-history",
    ],
  },
  { name: "java", fileExtensions: ["java", "jsp"] },
  {
    name: "docker",
    fileExtensions: [
      "dockerignore",
      "dockerfile",
      "docker-compose.yml",
      "docker-compose.yaml",
      "compose.yaml",
      "compose.yml",
    ],
    fileNames: [
      "dockerfile",
      "dockerfile.prod",
      "dockerfile.production",
      "dockerfile.alpha",
      "dockerfile.beta",
      "dockerfile.stage",
      "dockerfile.staging",
      "dockerfile.dev",
      "dockerfile.development",
      "dockerfile.local",
      "dockerfile.test",
      "dockerfile.testing",
      "dockerfile.ci",
      "dockerfile.web",
      "dockerfile.worker",
      "docker-compose.yml",
      "docker-compose.override.yml",
      "docker-compose.prod.yml",
      "docker-compose.production.yml",
      "docker-compose.alpha.yml",
      "docker-compose.beta.yml",
      "docker-compose.stage.yml",
      "docker-compose.staging.yml",
      "docker-compose.dev.yml",
      "docker-compose.development.yml",
      "docker-compose.local.yml",
      "docker-compose.test.yml",
      "docker-compose.testing.yml",
      "docker-compose.ci.yml",
      "docker-compose.web.yml",
      "docker-compose.worker.yml",

      "docker-compose.yaml",
      "docker-compose.override.yaml",
      "docker-compose.prod.yaml",
      "docker-compose.production.yaml",
      "docker-compose.alpha.yaml",
      "docker-compose.beta.yaml",
      "docker-compose.stage.yaml",
      "docker-compose.staging.yaml",
      "docker-compose.dev.yaml",
      "docker-compose.development.yaml",
      "docker-compose.local.yaml",
      "docker-compose.test.yaml",
      "docker-compose.testing.yaml",
      "docker-compose.ci.yaml",
      "docker-compose.web.yaml",
      "docker-compose.worker.yaml",

      "compose.yaml",
      "compose.override.yaml",
      "compose.prod.yaml",
      "compose.production.yaml",
      "compose.alpha.yaml",
      "compose.beta.yaml",
      "compose.stage.yaml",
      "compose.staging.yaml",
      "compose.dev.yaml",
      "compose.development.yaml",
      "compose.local.yaml",
      "compose.test.yaml",
      "compose.testing.yaml",
      "compose.ci.yaml",
      "compose.web.yaml",
      "compose.worker.yaml",

      "compose.yml",
      "compose.override.yml",
      "compose.prod.yml",
      "compose.production.yml",
      "compose.alpha.yml",
      "compose.beta.yml",
      "compose.stage.yml",
      "compose.staging.yml",
      "compose.dev.yml",
      "compose.development.yml",
      "compose.local.yml",
      "compose.test.yml",
      "compose.testing.yml",
      "compose.ci.yml",
      "compose.web.yml",
      "compose.worker.yml",
    ],
  },
  {
    name: "markdown",
    fileExtensions: ["md", "markdown", "rst", "mdx"],
  },
  {
    name: "svg",
    fileExtensions: ["svg"],
  },
];

export const folderIcon = [
  {
    name: "folder-public",
    folderNames: [
      "_site",
      "public",
      "www",
      "wwwroot",
      "web",
      "website",
      "site",
      "browser",
      "browsers",
    ],
  },
  {
    name: "folder-src",
    folderNames: ["src", "srcs", "source", "sources", "code"],
  },
  {
    name: "folder-node",
    folderNames: ["node_modules"],
  },
];
